version: 2

multi-ecosystem-groups:
  sdk-updates:
    schedule:
      interval: "weekly"
      day: "wednesday"
      
updates:
  # .NET SDK 
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    multi-ecosystem-group: "sdk-updates"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"
        
  # Docker
  - package-ecosystem: "docker"
    directory: "/src/RolandK.TimeTrack.Service"
    multi-ecosystem-group: "sdk-updates"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # NPM (Vue.js Client app)
  - package-ecosystem: "npm"
    directory: "/src/RolandK.TimeTrack.Service/ClientApp"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Nuget for all .NET projects   
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      all-dependencies:
        patterns:
          - "*"