# noinspection ComposeUnknownKeys
name: "rolandk-time-track-compose"

services:
  rk-time-track:
    container_name: rk-time-track
    image: rk-time-track-service
    build:
      context: ../
      dockerfile: ./src/RolandK.TimeTrack.Service/Dockerfile
    ports: 
      - "5200:80"
    environment:
      FileBasedTimeTrackingRepository__PersistenceFileDataStore__Type: "FileSystem"
      FileBasedTimeTrackingRepository__PersistenceFileDataStore__FileSystemRootPath: "/var/opt/rk-time-track/store"
      FileBasedTimeTrackingRepository__WriteIndentedJson: "true"
      StaticTopicRepository__SourceFilePath: "topics.json"
      StaticTopicRepository__FileDataStore__Type: "FileSystem"
      StaticTopicRepository__FileDataStore__FileSystemRootPath: "/var/opt/rk-time-track/testdata/"
    volumes:
      - type: bind
        source: ../testdata/runtimedata
        target: /var/opt/rk-time-track/store
      - type: bind
        source: ../testdata/masterdata
        target: /var/opt/rk-time-track/testdata