//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class TimeTrackClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    updateDay(body: UpdateDay_Request): Promise<TimeTrackingDay> {
        let url_ = this.baseUrl + "/api/ui/day";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateDay(_response);
        });
    }

    protected processUpdateDay(response: Response): Promise<TimeTrackingDay> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TimeTrackingDay.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingDay>(null as any);
    }

    /**
     * @return OK
     */
    searchEntries(body: SearchEntriesByText_Request): Promise<TimeTrackingEntry[]> {
        let url_ = this.baseUrl + "/api/ui/entries";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearchEntries(_response);
        });
    }

    protected processSearchEntries(response: Response): Promise<TimeTrackingEntry[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TimeTrackingEntry.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingEntry[]>(null as any);
    }

    /**
     * @return OK
     */
    getState(): Promise<TimeTrackApplicationState> {
        let url_ = this.baseUrl + "/api/ui/state";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetState(_response);
        });
    }

    protected processGetState(response: Response): Promise<TimeTrackApplicationState> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TimeTrackApplicationState.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackApplicationState>(null as any);
    }

    /**
     * @return OK
     */
    getAllTopics(): Promise<TimeTrackingTopic[]> {
        let url_ = this.baseUrl + "/api/ui/topics";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllTopics(_response);
        });
    }

    protected processGetAllTopics(response: Response): Promise<TimeTrackingTopic[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TimeTrackingTopic.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingTopic[]>(null as any);
    }

    /**
     * @return OK
     */
    getCurrentWeek(): Promise<TimeTrackingWeek> {
        let url_ = this.baseUrl + "/api/ui/week";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCurrentWeek(_response);
        });
    }

    protected processGetCurrentWeek(response: Response): Promise<TimeTrackingWeek> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TimeTrackingWeek.fromJS(resultData200);
            return result200;
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingWeek>(null as any);
    }

    /**
     * @return OK
     */
    getWeek(year: number, weekNumber: number): Promise<TimeTrackingWeek> {
        let url_ = this.baseUrl + "/api/ui/week/{year}/{weekNumber}";
        if (year === undefined || year === null)
            throw new globalThis.Error("The parameter 'year' must be defined.");
        url_ = url_.replace("{year}", encodeURIComponent("" + year));
        if (weekNumber === undefined || weekNumber === null)
            throw new globalThis.Error("The parameter 'weekNumber' must be defined.");
        url_ = url_.replace("{weekNumber}", encodeURIComponent("" + weekNumber));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWeek(_response);
        });
    }

    protected processGetWeek(response: Response): Promise<TimeTrackingWeek> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TimeTrackingWeek.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingWeek>(null as any);
    }

    /**
     * @return OK
     */
    getYearMetadata(year: number): Promise<TimeTrackingYearMetadata> {
        let url_ = this.baseUrl + "/api/ui/year/{year}/metadata";
        if (year === undefined || year === null)
            throw new globalThis.Error("The parameter 'year' must be defined.");
        url_ = url_.replace("{year}", encodeURIComponent("" + year));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetYearMetadata(_response);
        });
    }

    protected processGetYearMetadata(response: Response): Promise<TimeTrackingYearMetadata> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TimeTrackingYearMetadata.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TimeTrackingYearMetadata>(null as any);
    }
}

export class ProblemDetails implements IProblemDetails {
    type!: string | undefined;
    title!: string | undefined;
    status!: number | undefined;
    detail!: string | undefined;
    instance!: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }

    clone(): ProblemDetails {
        const json = this.toJSON();
        let result = new ProblemDetails();
        result.init(json);
        return result;
    }
}

export interface IProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export class SearchEntriesByText_Request implements ISearchEntriesByText_Request {
    searchText!: string | undefined;
    maxSearchResults!: number;

    constructor(data?: ISearchEntriesByText_Request) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.searchText = _data["searchText"];
            this.maxSearchResults = _data["maxSearchResults"];
        }
    }

    static fromJS(data: any): SearchEntriesByText_Request {
        data = typeof data === 'object' ? data : {};
        let result = new SearchEntriesByText_Request();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["searchText"] = this.searchText;
        data["maxSearchResults"] = this.maxSearchResults;
        return data;
    }

    clone(): SearchEntriesByText_Request {
        const json = this.toJSON();
        let result = new SearchEntriesByText_Request();
        result.init(json);
        return result;
    }
}

export interface ISearchEntriesByText_Request {
    searchText: string | undefined;
    maxSearchResults: number;
}

export class TimeTrackApplicationState implements ITimeTrackApplicationState {
    serviceStartupTimestamp!: Date;
    lastSuccessfulExport!: Date | undefined;

    constructor(data?: ITimeTrackApplicationState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.serviceStartupTimestamp = _data["serviceStartupTimestamp"] ? new Date(_data["serviceStartupTimestamp"].toString()) : undefined as any;
            this.lastSuccessfulExport = _data["lastSuccessfulExport"] ? new Date(_data["lastSuccessfulExport"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TimeTrackApplicationState {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackApplicationState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["serviceStartupTimestamp"] = this.serviceStartupTimestamp ? this.serviceStartupTimestamp.toISOString() : undefined as any;
        data["lastSuccessfulExport"] = this.lastSuccessfulExport ? this.lastSuccessfulExport.toISOString() : undefined as any;
        return data;
    }

    clone(): TimeTrackApplicationState {
        const json = this.toJSON();
        let result = new TimeTrackApplicationState();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackApplicationState {
    serviceStartupTimestamp: Date;
    lastSuccessfulExport: Date | undefined;
}

export class TimeTrackingDay implements ITimeTrackingDay {
    /** Date in format 'yyyy-mm-dd' */
    date!: string;
    type!: TimeTrackingDayType;
    entries!: TimeTrackingEntry[] | undefined;

    constructor(data?: ITimeTrackingDay) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"];
            this.type = _data["type"];
            if (Array.isArray(_data["entries"])) {
                this.entries = [] as any;
                for (let item of _data["entries"])
                    this.entries!.push(TimeTrackingEntry.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TimeTrackingDay {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingDay();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date;
        data["type"] = this.type;
        if (Array.isArray(this.entries)) {
            data["entries"] = [];
            for (let item of this.entries)
                data["entries"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }

    clone(): TimeTrackingDay {
        const json = this.toJSON();
        let result = new TimeTrackingDay();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingDay {
    /** Date in format 'yyyy-mm-dd' */
    date: string;
    type: TimeTrackingDayType;
    entries: TimeTrackingEntry[] | undefined;
}

export enum TimeTrackingDayType {
    WorkingDay = "WorkingDay",
    OwnEducation = "OwnEducation",
    PublicHoliday = "PublicHoliday",
    Ill = "Ill",
    Training = "Training",
    TrainingPreparation = "TrainingPreparation",
    Holiday = "Holiday",
    CompensatoryTimeOff = "CompensatoryTimeOff",
    Weekend = "Weekend",
}

export class TimeTrackingEntry implements ITimeTrackingEntry {
    topic!: TimeTrackingTopicReference;
    effortInHours!: number;
    effortBilled!: number;
    type!: TimeTrackingEntryType;
    description!: string | undefined;

    constructor(data?: ITimeTrackingEntry) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.topic = _data["topic"] ? TimeTrackingTopicReference.fromJS(_data["topic"]) : undefined as any;
            this.effortInHours = _data["effortInHours"];
            this.effortBilled = _data["effortBilled"];
            this.type = _data["type"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): TimeTrackingEntry {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingEntry();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["topic"] = this.topic ? this.topic.toJSON() : undefined as any;
        data["effortInHours"] = this.effortInHours;
        data["effortBilled"] = this.effortBilled;
        data["type"] = this.type;
        data["description"] = this.description;
        return data;
    }

    clone(): TimeTrackingEntry {
        const json = this.toJSON();
        let result = new TimeTrackingEntry();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingEntry {
    topic: TimeTrackingTopicReference;
    effortInHours: number;
    effortBilled: number;
    type: TimeTrackingEntryType;
    description: string | undefined;
}

export enum TimeTrackingEntryType {
    Default = "Default",
    Training = "Training",
    OnCall = "OnCall",
}

export class TimeTrackingTopic implements ITimeTrackingTopic {
    category!: string | undefined;
    name!: string | undefined;
    canBeInvoiced!: boolean;
    budget!: number | undefined;
    /** Date in format 'yyyy-mm-dd' */
    startDate!: string | undefined;
    /** Date in format 'yyyy-mm-dd' */
    endDate!: string | undefined;

    constructor(data?: ITimeTrackingTopic) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.category = _data["category"];
            this.name = _data["name"];
            this.canBeInvoiced = _data["canBeInvoiced"];
            this.budget = _data["budget"];
            this.startDate = _data["startDate"];
            this.endDate = _data["endDate"];
        }
    }

    static fromJS(data: any): TimeTrackingTopic {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingTopic();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["category"] = this.category;
        data["name"] = this.name;
        data["canBeInvoiced"] = this.canBeInvoiced;
        data["budget"] = this.budget;
        data["startDate"] = this.startDate;
        data["endDate"] = this.endDate;
        return data;
    }

    clone(): TimeTrackingTopic {
        const json = this.toJSON();
        let result = new TimeTrackingTopic();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingTopic {
    category: string | undefined;
    name: string | undefined;
    canBeInvoiced: boolean;
    budget: number | undefined;
    /** Date in format 'yyyy-mm-dd' */
    startDate: string | undefined;
    /** Date in format 'yyyy-mm-dd' */
    endDate: string | undefined;
}

export class TimeTrackingTopicReference implements ITimeTrackingTopicReference {
    category!: string | undefined;
    name!: string | undefined;

    constructor(data?: ITimeTrackingTopicReference) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.category = _data["category"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): TimeTrackingTopicReference {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingTopicReference();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["category"] = this.category;
        data["name"] = this.name;
        return data;
    }

    clone(): TimeTrackingTopicReference {
        const json = this.toJSON();
        let result = new TimeTrackingTopicReference();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingTopicReference {
    category: string | undefined;
    name: string | undefined;
}

export class TimeTrackingWeek implements ITimeTrackingWeek {
    year!: number;
    weekNumber!: number;
    monday!: TimeTrackingDay;
    tuesday!: TimeTrackingDay;
    wednesday!: TimeTrackingDay;
    thursday!: TimeTrackingDay;
    friday!: TimeTrackingDay;
    saturday!: TimeTrackingDay;
    sunday!: TimeTrackingDay;

    constructor(data?: ITimeTrackingWeek) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.year = _data["year"];
            this.weekNumber = _data["weekNumber"];
            this.monday = _data["monday"] ? TimeTrackingDay.fromJS(_data["monday"]) : undefined as any;
            this.tuesday = _data["tuesday"] ? TimeTrackingDay.fromJS(_data["tuesday"]) : undefined as any;
            this.wednesday = _data["wednesday"] ? TimeTrackingDay.fromJS(_data["wednesday"]) : undefined as any;
            this.thursday = _data["thursday"] ? TimeTrackingDay.fromJS(_data["thursday"]) : undefined as any;
            this.friday = _data["friday"] ? TimeTrackingDay.fromJS(_data["friday"]) : undefined as any;
            this.saturday = _data["saturday"] ? TimeTrackingDay.fromJS(_data["saturday"]) : undefined as any;
            this.sunday = _data["sunday"] ? TimeTrackingDay.fromJS(_data["sunday"]) : undefined as any;
        }
    }

    static fromJS(data: any): TimeTrackingWeek {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingWeek();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["year"] = this.year;
        data["weekNumber"] = this.weekNumber;
        data["monday"] = this.monday ? this.monday.toJSON() : undefined as any;
        data["tuesday"] = this.tuesday ? this.tuesday.toJSON() : undefined as any;
        data["wednesday"] = this.wednesday ? this.wednesday.toJSON() : undefined as any;
        data["thursday"] = this.thursday ? this.thursday.toJSON() : undefined as any;
        data["friday"] = this.friday ? this.friday.toJSON() : undefined as any;
        data["saturday"] = this.saturday ? this.saturday.toJSON() : undefined as any;
        data["sunday"] = this.sunday ? this.sunday.toJSON() : undefined as any;
        return data;
    }

    clone(): TimeTrackingWeek {
        const json = this.toJSON();
        let result = new TimeTrackingWeek();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingWeek {
    year: number;
    weekNumber: number;
    monday: TimeTrackingDay;
    tuesday: TimeTrackingDay;
    wednesday: TimeTrackingDay;
    thursday: TimeTrackingDay;
    friday: TimeTrackingDay;
    saturday: TimeTrackingDay;
    sunday: TimeTrackingDay;
}

export class TimeTrackingYearMetadata implements ITimeTrackingYearMetadata {
    maxWeekNumber!: number;

    constructor(data?: ITimeTrackingYearMetadata) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.maxWeekNumber = _data["maxWeekNumber"];
        }
    }

    static fromJS(data: any): TimeTrackingYearMetadata {
        data = typeof data === 'object' ? data : {};
        let result = new TimeTrackingYearMetadata();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["maxWeekNumber"] = this.maxWeekNumber;
        return data;
    }

    clone(): TimeTrackingYearMetadata {
        const json = this.toJSON();
        let result = new TimeTrackingYearMetadata();
        result.init(json);
        return result;
    }
}

export interface ITimeTrackingYearMetadata {
    maxWeekNumber: number;
}

export class UpdateDay_Request implements IUpdateDay_Request {
    /** Date in format 'yyyy-mm-dd' */
    date!: string;
    type!: TimeTrackingDayType;
    entries!: TimeTrackingEntry[] | undefined;

    constructor(data?: IUpdateDay_Request) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"];
            this.type = _data["type"];
            if (Array.isArray(_data["entries"])) {
                this.entries = [] as any;
                for (let item of _data["entries"])
                    this.entries!.push(TimeTrackingEntry.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateDay_Request {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateDay_Request();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date;
        data["type"] = this.type;
        if (Array.isArray(this.entries)) {
            data["entries"] = [];
            for (let item of this.entries)
                data["entries"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }

    clone(): UpdateDay_Request {
        const json = this.toJSON();
        let result = new UpdateDay_Request();
        result.init(json);
        return result;
    }
}

export interface IUpdateDay_Request {
    /** Date in format 'yyyy-mm-dd' */
    date: string;
    type: TimeTrackingDayType;
    entries: TimeTrackingEntry[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}