name: Continuous integration

on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - src/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and test
      shell: pwsh
      working-directory: ./scripts
      run: ./build-and-test.ps1